module GLS.Languages {
    export var CSharp: Language = new GLS.Language()
        .setName("CSharp")
        .setExtension("cs")
        .setPrintFunction("System.Console.WriteLine")
        .setSemiColon(";")
        .setClassConstructorName("") // should default to using class name, then delete here
        .setClassEnder("};")
        .setClassFunctionsTakeThis(false)
        .setClassFunctionsStart("")
        .setClassNewer("new ")
        .setClassPrivacy(true)
        .setClassStartLeft("class ")
        .setClassStartRight(" {")
        .setClassThis("this")
        .setClassThisAccess(".")
        .setCommentorBlockStart("/*")
        .setCommentorBlockEnd("*/")
        .setCommentorInline("//")
        .setConditionStartLeft(" (")
        .setConditionStartRight(") {")
        .setConditionContinueLeft("} ")
        .setConditionContinueRight(" {")
        .setConditionEnd("}")
        .setFileEndLine("}")
        .setFileStartLeft("public class ")
        .setFileStartRight(" {")
        .setFunctionDefine("")
        .setFunctionDefineRight(" {")
        .setFunctionDefineEnd("}")
        .setFunctionReturnsExplicit(true)
        .setFunctionTypeAfterName(false)
        .setMainEndLine("}")
        .setMainStartLine("public static void Main() {")
        .setRangedForLoops(false)
        .setVariableDeclareStart("")
        .setVariableTypesExplicit(true)
        .setVariableTypesAfterName(false)
        .addTypeAlias("int", "number")
        .addTypeAlias("bool", "boolean");
}