module GLS.Languages {
    export var Ruby: Language = new GLS.Language()
        .setName("Ruby")
        .setExtension("rb")
        .setPrintFunction("puts")
        .setSemiColon("")
        .setArrayClass("")
        .setArrayLength("length")
        .setClassConstructorAsStatic(true)
        .setClassParentName("super")
        .setClassConstructorName("initialize")
        .setClassConstructorLoose(true)
        .setClassEnder("end")
        .setClassExtends("<")
        .setClassFunctionsStart("def ")
        .setClassFunctionsTakeThis(false)
        .setClassFunctionsThis("")
        .setClassMemberVariableDefault("")
        .setClassMemberVariablePrivacy(false)
        .setClassMemberVariableStarter("@")
        .setClassNewer("new")
        .setClassPrivacy(false)
        .setClassStartLeft("class ")
        .setClassStartRight("")
        .setClassThis("@")
        .setClassThisAccess("")
        .setCommentorBlockStart("=begin")
        .setCommentorBlockEnd("=end")
        .setCommentorInline("#")
        .setConditionStartLeft(" ")
        .setConditionStartRight("")
        .setConditionContinueLeft(" ")
        .setConditionContinueRight("")
        .setConditionEnd("end")
        .setFileEndLine("")
        .setFileStartLeft("")
        .setFileStartRight("")
        .setFunctionDefine("def ")
        .setFunctionDefineRight("")
        .setFunctionDefineEnd("end")
        .setMainEndLine("end")
        .setMainStartLine("if __FILE__ == $PROGRAM_NAME")
        .setToString(".to_s")
        .setRangedForLoops(true)
        .setRangedForLoopsStart(" in ")
        .setRangedForLoopsMiddle("..")
        .setRangedForLoopsEnd("")
        .setFunctionReturnsExplicit(false)
        .setVariableTypesExplicit(false)
        .setVariableDeclareStart("")
}