module GLS.Languages {
    export var Java: Language = new GLS.Language()
        .setName("Java")
        .setExtension("java")
        .setPrintFunction("System.out.println")
        .setSemiColon(";")
        .setArrayClass("Array")
        .setArrayInitializationAsNewTyped(true)
        .setArrayLength(".length")
        .setClassConstructorName("")
        .setClassEnder("};")
        .setClassExtends("extends")
        .setClassFunctionsTakeThis(false)
        .setClassFunctionsStart("")
        .setClassMemberVariableDefault("")
        .setClassMemberVariablePrivacy(true)
        .setClassMemberVariableStarter("")
        .setClassNewer("new ")
        .setClassParentName("super")
        .setClassPrivacy(true)
        .setClassStartLeft("class ")
        .setClassStartRight(" {")
        .setClassTemplates(true)
        .setClassTemplatesBetween(", ")
        .setClassThis("this")
        .setClassThisAccess(".")
        .setCommentorBlockStart("/*")
        .setCommentorBlockEnd("*/")
        .setCommentorInline("//")
        .setConditionStartLeft(" (")
        .setConditionStartRight(") {")
        .setConditionContinueLeft("} ")
        .setConditionContinueRight(" {")
        .setConditionEnd("}")
        .setDictionaryClass("HashMap")
        .setDictionaryInitializationAsNew(true)
        .setDictionaryKeyLeft("add(")
        .setDictionaryKeyMiddle(", ")
        .setDictionaryKeyRight(")")
        .setFileEndLine("}")
        .setFileStartLeft("public class ")
        .setFileStartRight(" {")
        .setFunctionDefine("")
        .setFunctionDefineRight(" {")
        .setFunctionDefineEnd("}")
        .setFunctionReturnsExplicit(true)
        .setFunctionTypeAfterName(false)
        .setMainEndLine("}")
        .setMainStartLine("public void main() {")
        .setToString("String.valueOf")
        .setToStringAsFunction(true)
        .setUndefined("null")
        .setRangedForLoops(false)
        .setVariableDeclareStart("")
        .setVariableTypesExplicit(true)
        .setVariableTypesAfterName(false)
        .addTypeAlias("int", "number")
        .addTypeAlias("String", "string")
}