module GLS.Languages {
    export var Python: Language = new GLS.Language()
        .setName("Python")
        .setExtension("py")
        .setPrintFunction("print")
        .setSemiColon("")
        .setClassConstructorName("def __init__")
        .setClassEnder("\0")
        .setClassFunctionsStart("def ")
        .setClassFunctionsTakeThis(true)
        .setClassFunctionsThis("self")
        .setClassMemberVariableDefault("None")
        .setClassMemberVariablePrivacy(false)
        .setClassMemberVariableStarter("")
        .setClassNewer("")
        .setClassPrivacy(false)
        .setClassStartLeft("class ")
        .setClassStartRight(":")
        .setClassThis("self")
        .setClassThisAccess(".")
        .setCommentorBlockStart("\"\"\"")
        .setCommentorBlockEnd("\"\"\"")
        .setCommentorInline("#")
        .setConditionStartLeft(" ")
        .setConditionStartRight(":")
        .setConditionContinueLeft(" ")
        .setConditionContinueRight(":")
        .setConditionEnd("\0")
        .setFileEndLine("")
        .setFileStartLeft("")
        .setFileStartRight("")
        .setFunctionDefine("def ")
        .setFunctionDefineRight(":")
        .setFunctionDefineEnd("\0")
        .setMainEndLine("\0")
        .setMainStartLine("if __name__ == '__main__':")
        .setToString("str")
        .setToStringAsFunction(true)
        .setRangedForLoops(true)
        .setRangedForLoopsStart(" in range(")
        .setRangedForLoopsMiddle(", ")
        .setRangedForLoopsEnd(")")
        .setFunctionReturnsExplicit(false)
        .setVariableTypesExplicit(false)
        .setVariableDeclareStart("")
        .addValueAlias("False", "false")
        .addValueAlias("True", "true");
}